"use client";

import React, { useState } from "react";
import { api } from "@/lib/api-client";
import {
  ScenarioExplanationRequest,
  ScenarioExplanationResponse,
  ShockEvent,
} from "@/types/api";
import {
  Sparkles,
  RefreshCw,
  ChevronDown,
  ChevronUp,
  AlertCircle,
  ShieldCheck,
  ArrowRight,
  Info,
  CheckCircle2,
  Cpu,
} from "lucide-react";

interface AIExplanationCardProps {
  goalId: string;
  explanationType: "health" | "stress_test" | "cascade" | "recovery" | "survival";
  shocks?: ShockEvent[];
  horizonMonths?: number;
  title?: string;
  className?: string;
  defaultExpanded?: boolean;
}

export function AIExplanationCard({
  goalId,
  explanationType,
  shocks,
  horizonMonths = 36,
  title = "Analytical Interpretation",
  className = "",
  defaultExpanded = false,
}: AIExplanationCardProps) {
  const [data, setData] = useState<ScenarioExplanationResponse | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [isExpanded, setIsExpanded] = useState(defaultExpanded);

  async function handleFetchExplanation() {
    if (!goalId) return;
    setLoading(true);
    setError(null);

    try {
      const res = await api.explainScenario({
        goal_id: goalId,
        explanation_type: explanationType,
        shocks,
        horizon_months: horizonMonths,
      });
      setData(res);
      setIsExpanded(true);
    } catch (err: any) {
      setError(
        err.message ||
          "AI explanation service unavailable. Your verified financial analysis remains fully accessible."
      );
    } finally {
      setLoading(false);
    }
  }

  return (
    <div
      className={`rounded-2xl border border-stone-200/80 bg-white shadow-soft-sm transition-all ${className}`}
    >
      {/* Top Banner & Control Bar */}
      <div className="p-4 sm:p-5 flex flex-col sm:flex-row sm:items-center justify-between gap-3 border-b border-stone-100 bg-stone-50/40 rounded-t-2xl">
        <div className="flex items-start gap-3">
          <div className="p-2 rounded-xl bg-stone-100 text-stone-700 shrink-0 mt-0.5">
            <Sparkles className="w-4 h-4 text-stone-700" />
          </div>
          <div>
            <div className="flex flex-wrap items-center gap-2">
              <span className="text-[10px] font-semibold text-stone-700 bg-stone-100/90 border border-stone-200/80 px-2.5 py-0.5 rounded-full uppercase tracking-wider">
                AI Explanation
              </span>
              <h3 className="text-xs font-semibold text-stone-950 tracking-tight">
                {title}
              </h3>
              {data && (
                <span
                  className={`inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-[10px] font-medium border ${
                    data.is_fallback
                      ? "bg-stone-100 text-stone-700 border-stone-200"
                      : "bg-emerald-50 text-emerald-800 border-emerald-200"
                  }`}
                >
                  <Cpu className="w-3 h-3" />
                  {data.is_fallback ? "Verified Fallback Engine" : "Gemini 1.5 Flash"}
                </span>
              )}
            </div>
            <p className="text-[11px] text-stone-500 mt-1 leading-relaxed">
              Financial calculations are generated by SaveSmart&apos;s deterministic financial engine. AI only explains verified results.
            </p>
          </div>
        </div>

        <div className="flex items-center gap-2 self-end sm:self-auto shrink-0">
          {!data && (
            <button
              type="button"
              onClick={handleFetchExplanation}
              disabled={loading || !goalId}
              className="inline-flex items-center gap-1.5 px-4 py-1.5 text-xs font-semibold text-white bg-stone-900 hover:bg-stone-800 rounded-full shadow-soft-sm transition-all disabled:opacity-50 active:scale-95"
            >
              {loading ? (
                <RefreshCw className="w-3.5 h-3.5 animate-spin" />
              ) : (
                <Sparkles className="w-3.5 h-3.5" />
              )}
              {loading ? "Analyzing..." : "Explain This Result"}
            </button>
          )}

          {data && (
            <div className="flex items-center gap-2">
              <button
                type="button"
                onClick={handleFetchExplanation}
                disabled={loading}
                className="p-1.5 text-stone-400 hover:text-stone-900 rounded-lg transition-colors"
                title="Refresh AI explanation"
              >
                <RefreshCw className={`w-3.5 h-3.5 ${loading ? "animate-spin" : ""}`} />
              </button>
              <button
                type="button"
                onClick={() => setIsExpanded(!isExpanded)}
                className="inline-flex items-center gap-1 text-xs font-medium text-stone-600 hover:text-stone-950 px-2.5 py-1 rounded-full border border-stone-200/80 bg-stone-50 hover:bg-white transition-colors"
              >
                <span>{isExpanded ? "Collapse" : "Expand"}</span>
                {isExpanded ? <ChevronUp className="w-3.5 h-3.5" /> : <ChevronDown className="w-3.5 h-3.5" />}
              </button>
            </div>
          )}
        </div>
      </div>

      {/* Error state */}
      {error && (
        <div className="p-4 text-xs text-amber-800 bg-amber-50/70 border-b border-amber-200 flex items-start gap-2">
          <AlertCircle className="w-4 h-4 shrink-0 text-amber-600 mt-0.5" />
          <div className="flex-1">
            <span>{error}</span>
            <div className="mt-1.5">
              <button
                type="button"
                onClick={handleFetchExplanation}
                className="text-[11px] font-semibold text-amber-900 underline hover:no-underline"
              >
                Retry Request
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Loading state indicator */}
      {loading && !data && (
        <div className="p-6 text-center text-xs text-slate-500 space-y-2">
          <RefreshCw className="w-5 h-5 animate-spin text-indigo-600 mx-auto" />
          <p className="font-medium text-slate-700">Synthesizing deterministic engine results...</p>
          <p className="text-[11px] text-slate-400">
            AI explanation is checked for numerical consistency with verified financial results.
          </p>
        </div>
      )}

      {/* Expanded Explanation Content */}
      {data && isExpanded && (
        <div className="p-5 sm:p-6 space-y-5 text-xs">
          {/* Headline Banner */}
          <div className="p-4 rounded-xl bg-stone-50 border border-stone-200/80">
            <h4 className="font-semibold text-stone-950 text-xs sm:text-sm leading-snug tracking-tight">
              {data.ai_explanation.headline}
            </h4>
          </div>

          {/* Narrative Summary */}
          <div className="space-y-1.5">
            <div className="font-semibold text-stone-700 text-[11px] uppercase tracking-wider">
              Analytical Narrative
            </div>
            <p className="text-stone-700 leading-relaxed bg-stone-50/50 p-4 rounded-xl border border-stone-200/60">
              {data.ai_explanation.summary}
            </p>
          </div>

          {/* Key Drivers */}
          {data.ai_explanation.key_drivers?.length > 0 && (
            <div className="space-y-2">
              <div className="font-semibold text-stone-700 text-[11px] uppercase tracking-wider">
                Primary Financial Drivers
              </div>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-2.5">
                {data.ai_explanation.key_drivers.map((driver, idx) => (
                  <div
                    key={idx}
                    className="p-3 rounded-xl bg-stone-50/50 border border-stone-200/60 flex items-start gap-2.5"
                  >
                    <ArrowRight className="w-3.5 h-3.5 text-stone-900 shrink-0 mt-0.5" />
                    <span className="text-stone-700 leading-relaxed">{driver}</span>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Impact & Trade-Offs Grid */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
            {/* Impact Assessment */}
            <div className="p-4 rounded-xl bg-stone-50/50 border border-stone-200/60 space-y-1.5">
              <div className="font-semibold text-stone-700 text-[11px] uppercase tracking-wider">
                Liquidity & Timeline Impact
              </div>
              <p className="text-stone-600 leading-relaxed">
                {data.ai_explanation.impact_assessment}
              </p>
            </div>

            {/* Trade-Offs Explained */}
            {data.ai_explanation.trade_offs_explained && (
              <div className="p-4 rounded-xl bg-stone-50/50 border border-stone-200/60 space-y-1.5">
                <div className="font-semibold text-stone-700 text-[11px] uppercase tracking-wider">
                  Strategic Trade-Offs
                </div>
                <p className="text-stone-600 leading-relaxed">
                  {data.ai_explanation.trade_offs_explained}
                </p>
              </div>
            )}
          </div>

          {/* Actionable Next Steps (Strictly Budgeting, NOT Investment Advice) */}
          {data.ai_explanation.actionable_next_steps?.length > 0 && (
            <div className="space-y-2 pt-1">
              <div className="font-semibold text-stone-700 text-[11px] uppercase tracking-wider">
                Pragmatic Resilience Steps
              </div>
              <div className="space-y-2">
                {data.ai_explanation.actionable_next_steps.map((step, idx) => (
                  <div
                    key={idx}
                    className="p-3 rounded-xl bg-emerald-50/60 border border-emerald-200/70 flex items-start gap-2.5"
                  >
                    <CheckCircle2 className="w-3.5 h-3.5 text-emerald-700 shrink-0 mt-0.5" />
                    <span className="text-stone-800 leading-relaxed">{step}</span>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Mandatory Engine Disclaimer */}
          <div className="pt-3 border-t border-stone-100 flex items-start gap-2 text-[10px] text-stone-400">
            <ShieldCheck className="w-3.5 h-3.5 text-emerald-600 shrink-0 mt-0.5" />
            <span className="leading-normal">{data.disclaimer}</span>
          </div>
        </div>
      )}
    </div>
  );
}
